spring:
  application:
    name: moonlight
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=30s
    cache-names:
      - vorlagen
      - pages
      - labels
      - mapping-config
      - product-data
      - vorlage-history
server:
  servlet:
    context-path: /moonlight
  port: 8078
elasticsearch:
  host: localhost
  port: 9200
